mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/nodejs-18.8.0", target = "/opt/nodejs-18.8.0" },
]

[limits]
# as = 256000000  # use --max-old-space-size=256
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
nofile = 32     # 32 max fd
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "capget",
  "clone",
  "close",
  "dup3",
  "epoll_create1",
  "epoll_ctl",
  "epoll_wait",
  "eventfd2",
  "execve",
  "exit",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getcwd",
  "getegid",
  "geteuid",
  "getgid",
  "getpid",
  "getrandom",
  "gettid",
  "getuid",
  "ioctl",
  "madvise",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pipe2",
  "pkey_alloc",
  "pkey_free",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "statx",
  "sysinfo",
  "tgkill",
  "uname",
  "write",
]
