[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.toml" }}

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}
]
