mounts = [
  { source = "/dev/null"          , target = "/dev/null"            , rw = true },
  { source = "/lib"               , target = "/lib"                },
  { source = "/lib64"             , target = "/lib64"              },
  { source = "/usr/lib"           , target = "/usr/lib"            },
  { source = "/usr/lib64"         , target = "/usr/lib64"          },
  { source = "/usr/bin/bash"      , target = "/usr/bin/bash"       },
  { source = "/usr/bin/dirname"   , target = "/usr/bin/dirname"    },
  { source = "/usr/bin/env"       , target = "/usr/bin/env"        },
  { source = "/usr/bin/uname"     , target = "/usr/bin/uname"      },
  { source = "/usr/bin/which"     , target = "/usr/bin/which"      },
  { source = "/usr/share/terminfo", target = "/usr/share/terminfo" },
  { source = "/opt/openjdk-18"    , target = "/opt/openjdk-18"     },
  { source = "/opt/scala-3.1.3"   , target = "/opt/scala-3.1.3"    },
]

[env]
SCALA_HOME = "/opt/scala-3.1.3"
JAVA_HOME = "/opt/openjdk-18"
PATH = "/opt/scala-3.1.3/bin:/opt/openjdk-18/bin:/usr/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
