[lang.scala]
name = "Scala (3.1.3)"

[lang.scala.compile]
command = ["/opt/scala-3.1.3/bin/scalac", "main.scala"]
sandbox = "embed://lang-scala/compilebox.toml"

[lang.scala.execute]
command = ["/opt/scala-3.1.3/bin/scala", "-J-Xmx256m", "Main"]
sandbox = "embed://lang-scala/executebox.toml"
