# Ref: https://github.com/google/sandboxed-api/blob/main/sandboxed_api/sandbox2/policybuilder.h

# Required by hakoniwa
"execve",

# AllowStaticStartup
"arch_prctl",
"brk",
"futex",
"readlink",
"set_robust_list",
"set_tid_address",
"uname",

# AllowDynamicStartup
"fcntl",
"getcwd",
"mprotect",
"munmap",
"sysinfo",

# AllowExit
"exit",
"exit_group",

# AllowHandleSignals
"rt_sigaction",
"rt_sigprocmask",
"rt_sigreturn",
"sigaltstack",
"tgkill",

# AllowRestartableSequencesWithProcFiles
"mmap",
"rseq",
"sched_getaffinity",
"sched_setaffinity",
"sched_yield",

# AllowEpoll
"epoll_create1",
"epoll_create",
"epoll_ctl",
"epoll_wait",
"poll",
"ppoll",

# AllowTCGETS
"ioctl",

# AllowGetIDs
"getgid",
"getuid",
"getegid",
"geteuid",

# AllowGetPIDs
"getpid",
"getpgrp",
"getppid",
"gettid",

# AllowGetRlimit
"getrlimit",
"prlimit64",

# AllowGetRandom
"getrandom",

# AllowTime
"clock_getres",
"clock_gettime",
"gettimeofday",
"time",

# AllowSleep
"clock_nanosleep",
"nanosleep",

# AllowStat
"fstat",
"fstat64",
"lstat",
"lstat64",
"newfstatat",
"stat",
"statx",

# AllowAccess
"access",
"faccessat2",
"faccessat",

# AllowOpen
"close",
"lseek",
"open",
"openat",

# AllowRead
"pread64",
"read",
"readv",

# AllowWrite
"write",
"writev",

# AllowReaddir
"getdents64",
