[env]
LANG     = {{ os_env "LANG"     }}
LANGUAGE = {{ os_env "LANGUAGE" }}
LC_ALL   = {{ os_env "LC_ALL"   }}

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "execve",
  "arch_prctl",
  "brk",
  "futex",
  "readlink",
  "set_robust_list",
  "set_tid_address",
  "uname",
  "fcntl",
  "getcwd",
  "mprotect",
  "munmap",
  "sysinfo",
  "exit",
  "exit_group",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sigaltstack",
  "tgkill",
  "mmap",
  "rseq",
  "sched_getaffinity",
  "sched_setaffinity",
  "sched_yield",
  "epoll_create1",
  "epoll_create",
  "epoll_ctl",
  "epoll_wait",
  "poll",
  "ppoll",
  "ioctl",
  "getgid",
  "getuid",
  "getegid",
  "geteuid",
  "getpid",
  "getpgrp",
  "getppid",
  "gettid",
  "getrlimit",
  "prlimit64",
  "getrandom",
  "clock_getres",
  "clock_gettime",
  "gettimeofday",
  "time",
  "clock_nanosleep",
  "nanosleep",
  "fstat",
  "fstat64",
  "lstat",
  "lstat64",
  "newfstatat",
  "stat",
  "statx",
  "access",
  "faccessat2",
  "faccessat",
  "close",
  "lseek",
  "open",
  "openat",
  "pread64",
  "read",
  "readv",
  "write",
  "writev",
  "getdents64",
]
