[lang.c]
name = "C (GCC 10.2.1)"

[lang.c.compile]
command = ["/usr/bin/gcc", "-std=c11", "-O2", "--static", "main.c", "-o", "main"]
sandbox = "lang-c/compilebox.toml"

[lang.c.execute]
command = ["/hako/main"]
sandbox = "lang-c/executebox.toml"
