mounts = [
  { source = "/lib"           , target = "/lib"            },
  { source = "/lib64"         , target = "/lib64"          },
  { source = "/usr/lib"       , target = "/usr/lib"        },
  { source = "/usr/lib64"     , target = "/usr/lib64"      },
  { source = "/opt/ruby-3.1.2", target = "/opt/ruby-3.1.2" },
]

[env]
PATH     = "/opt/ruby-3.1.2/bin"
LANG     = {{ os_env "LANG"     }}
LANGUAGE = {{ os_env "LANGUAGE" }}
LC_ALL   = {{ os_env "LC_ALL"   }}

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_gettime",
  "close",
  "connect",
  "dup",
  "eventfd2",
  "execve",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getpid",
  "getrandom",
  "gettid",
  "getuid",
  "ioctl",
  "lseek",
  "lstat",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "prctl",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "sched_getaffinity",
  "sched_yield",
  "sigaltstack",
  "socket",
  "stat",
  "sysinfo",
  "timer_create",
  "timer_delete",
  "write",
]
