mounts = [
  { source = "/bin"              , target = "/bin"               },
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/bin"          , target = "/usr/bin"           },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/usr/include"      , target = "/usr/include"       },
  { source = "/opt/haskell-9.4.2", target = "/opt/haskell-9.4.2" },
]

[[files]]
target = "/tmp/.keep"
contents = ""

[env]
PATH = "/opt/haskell-9.4.2/.ghcup/bin:/usr/bin:/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
