mounts = [
  { source = "/lib"      , target = "/lib"       },
  { source = "/lib64"    , target = "/lib64"     },
  { source = "/usr/lib"  , target = "/usr/lib"   },
  { source = "/usr/lib64", target = "/usr/lib64" },
]

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_gettime",
  "clone",
  "close",
  "execve",
  "exit",
  "exit_group",
  "futex",
  "getrandom",
  "ioctl",
  "madvise",
  "mmap",
  "mprotect",
  "newfstatat",
  "openat",
  "poll",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "set_robust_list",
  "set_tid_address",
  "sysinfo",
  "timerfd_create",
  "timerfd_settime",
  "write",
]
