[lang.java]
name = "Java (OpenJDK 18)"

[lang.java.compile]
command = ["/opt/openjdk-18/bin/javac", "main.java"]
sandbox = ".devcontainer/shared/compilebox.toml"

[lang.java.execute]
command = ["/opt/openjdk-18/bin/java", "-Xmx256m", "Main"]
sandbox = ".devcontainer/lang-java/executebox.toml"
