mounts = [
  { source = "/lib"           , target = "/lib"            },
  { source = "/lib64"         , target = "/lib64"          },
  { source = "/usr/lib"       , target = "/usr/lib"        },
  { source = "/usr/lib64"     , target = "/usr/lib64"      },
  { source = "/opt/openjdk-18", target = "/opt/openjdk-18" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}
JAVA_HOME = "/opt/openjdk-18"

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use -Xmx256m

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"clone",
"connect",
"getrusage",
"madvise",
"prctl",
"socket",
]
