mounts = [
  { source = "/lib"      , target = "/lib"       },
  { source = "/lib64"    , target = "/lib64"     },
  { source = "/usr/lib"  , target = "/usr/lib"   },
  { source = "/usr/lib64", target = "/usr/lib64" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.toml" }}

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_getres",
  "close",
  "execve",
  "exit_group",
  "fstat",
  "getrandom",
  "lstat",
  "mmap",
  "mprotect",
  "newfstatat",
  "openat",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "set_robust_list",
  "set_tid_address",
  "stat",
  "write",
]
