mounts = [
  { source = "/dev/null"         , target = "/dev/null"           , rw = true },
  { source = "/bin"              , target = "/bin"               },
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/bin"          , target = "/usr/bin"           },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/erlang-25.0.4", target = "/opt/erlang-25.0.4" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use +MMscs256

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"bind",
"chdir",
"clone",
"close_range",
"connect",
"dup2",
"dup",
"ftruncate",
"getsockname",
"getsockopt",
"madvise",
"memfd_create",
"pipe2",
"pipe",
"ppoll",
"prctl",
"pselect6",
"recvmsg",
"sendmsg",
"select",
"setsid",
"setsockopt",
"socket",
"socketpair",
"timerfd_create",
"timerfd_settime",
"wait4",
]
