mounts = [
  { source = "/dev/null"         , target = "/dev/null"           , rw = true },
  { source = "/bin"              , target = "/bin"               },
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/bin"          , target = "/usr/bin"           },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/erlang-25.0.4", target = "/opt/erlang-25.0.4" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use +MMscs256

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "bind",
  "brk",
  "chdir",
  "clone",
  "close",
  "close_range",
  "connect",
  "dup",
  "dup2",
  "epoll_create",
  "epoll_ctl",
  "epoll_wait",
  "execve",
  "exit",
  "exit_group",
  "fcntl",
  "fstat",
  "ftruncate",
  "futex",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getpgrp",
  "getpid",
  "getppid",
  "getrandom",
  "getsockname",
  "getsockopt",
  "getuid",
  "ioctl",
  "kill",
  "lseek",
  "lstat",
  "madvise",
  "memfd_create",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pipe",
  "pipe2",
  "ppoll",
  "prctl",
  "pread64",
  "prlimit64",
  "pselect6",
  "read",
  "readlink",
  "readv",
  "recvmsg",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "select",
  "sendmsg",
  "set_robust_list",
  "setsid",
  "setsockopt",
  "set_tid_address",
  "sigaltstack",
  "socket",
  "socketpair",
  "stat",
  "sysinfo",
  "timerfd_create",
  "timerfd_settime",
  "uname",
  "wait4",
  "write",
  "writev",
]
