[env]
GOMEMLIMIT = "256000000"

[limits]
# as = 256000000  # use GOMEMLIMIT
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "arch_prctl",
  "clone",
  "close",
  "execve",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getpid",
  "getrlimit",
  "gettid",
  "lstat",
  "madvise",
  "mmap",
  "nanosleep",
  "openat",
  "read",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "setrlimit",
  "sigaltstack",
  "stat",
  "write",
]
