[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}
GOMEMLIMIT = "256000000"

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use GOMEMLIMIT

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"clone",
"setrlimit",
]
