[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}
GOMEMLIMIT = "256000000"

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use GOMEMLIMIT

[seccomp]
syscalls = [
  "arch_prctl",
  "clone",
  "close",
  "execve",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getpid",
  "getrlimit",
  "gettid",
  "lstat",
  "madvise",
  "mmap",
  "nanosleep",
  "openat",
  "read",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "setrlimit",
  "sigaltstack",
  "stat",
  "tgkill",
  "write",
]
