[lang.cpp]
name = "C++ (GCC unknown)"

[lang.cpp.compile]
command = ["/usr/bin/g++", "-std=c++14", "-O2", "--static", "main.cpp", "-o", "main"]
sandbox = "embed://lang-cpp/compilebox.toml"

[lang.cpp.execute]
command = ["/hako/main"]
sandbox = "embed://lang-cpp/executebox.toml"
