[server]
ip = "0.0.0.0"
port = 8080

[lang.c]
name = "C (GCC)"

[lang.c.compile]
command = ["/usr/bin/gcc", "--static", "main.c", "-o", "main"]
sandbox = "lang-c/compilebox.toml"

[lang.c.execute]
command = ["/hako/main"]
sandbox = "lang-c/executebox.toml"
