mounts = [
  { source = "/dev/null"         , target = "/dev/null"           , rw = true },
  { source = "/bin"              , target = "/bin"               },
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/bin"          , target = "/usr/bin"           },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/erlang-25.0.4", target = "/opt/erlang-25.0.4" },
]

[env]
PATH = "/opt/erlang-25.0.4/bin:/usr/bin:/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
