[lang.erlang]
name = "Erlang (25.0.4)"

[lang.erlang.compile]
command = ["/opt/erlang-25.0.4/bin/erlc", "main.erl"]
sandbox = "embed://lang-erlang/compilebox.toml"

[lang.erlang.execute]
command = ["/opt/erlang-25.0.4/bin/erl", "+MMscs256", "-noshell", "-s main start", "-s init stop"]
sandbox = "embed://lang-erlang/executebox.toml"
