mounts = [
  { source = "/dev/null"         , target = "/dev/null"           , rw = true },
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/usr/bin/basename" , target = "/usr/bin/basename"  },
  { source = "/usr/bin/bash"     , target = "/usr/bin/bash"      },
  { source = "/usr/bin/dirname"  , target = "/usr/bin/dirname"   },
  { source = "/usr/bin/sh"       , target = "/usr/bin/sh"        },
  { source = "/bin/bash"         , target = "/bin/bash"          },
  { source = "/bin/sh"           , target = "/bin/sh"            },
  { source = "/opt/erlang-25.0.4", target = "/opt/erlang-25.0.4" },
]

[env]
PATH = "/opt/erlang-25.0.4/bin:/usr/bin:/bin"

[limits]
# as = 256000000  # use +MMscs256
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "bind",
  "brk",
  "chdir",
  "clone",
  "close",
  "close_range",
  "connect",
  "dup",
  "dup2",
  "epoll_create",
  "epoll_ctl",
  "epoll_wait",
  "execve",
  "exit",
  "exit_group",
  "fcntl",
  "ftruncate",
  "futex",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getpgrp",
  "getpid",
  "getppid",
  "getrandom",
  "getsockname",
  "getsockopt",
  "getuid",
  "ioctl",
  "kill",
  "lseek",
  "madvise",
  "memfd_create",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pipe2",
  "ppoll",
  "prctl",
  "pread64",
  "prlimit64",
  "pselect6",
  "read",
  "readlink",
  "readv",
  "recvmsg",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "sendmsg",
  "set_robust_list",
  "setsid",
  "setsockopt",
  "set_tid_address",
  "sigaltstack",
  "socket",
  "socketpair",
  "sysinfo",
  "timerfd_create",
  "timerfd_settime",
  "uname",
  "wait4",
  "write",
  "writev",
]
