[lang.c]
name = "C"

[lang.c.compile]
command = ["/usr/bin/gcc", "-std=c11", "-O2", "--static", "main.c", "-o", "main"]
sandbox = "embed://policies/c.compilebox.toml"

[lang.c.execute]
command = ["/hako/main"]
sandbox = "embed://policies/c.executebox.toml"


[lang.cpp]
name = "C Plus Plus"

[lang.cpp.compile]
command = ["/usr/bin/g++", "-std=c++14", "-O2", "--static", "main.cpp", "-o", "main"]
sandbox = "embed://policies/cpp.compilebox.toml"

[lang.cpp.execute]
command = ["/hako/main"]
sandbox = "embed://policies/cpp.executebox.toml"


[lang.go]
name = "Golang (1.19)"

[lang.go.compile]
command = ["/opt/go-1.19/bin/go", "build", "main.go"]
sandbox = "embed://policies/go.compilebox.toml"

[lang.go.execute]
command = ["/hako/main"]
sandbox = "embed://policies/go.executebox.toml"


[lang.java]
name = "Java (OpenJDK 18)"

[lang.java.compile]
command = ["/opt/openjdk-18/bin/javac", "main.java"]
sandbox = "embed://policies/java.compilebox.toml"

[lang.java.execute]
command = ["/opt/openjdk-18/bin/java", "-Xmx256m", "Main"]
sandbox = "embed://policies/java.executebox.toml"
