[lang.c]
name = "C"

[lang.c.compile]
command = ["/usr/bin/gcc", "--static", "main.c", "-o", "main"]
sandbox = "embed://policies/c.compilebox.toml"

[lang.c.execute]
command = ["/hako/main"]
sandbox = "embed://policies/c.executebox.toml"


[lang.cpp]
name = "C Plus Plus"

[lang.cpp.compile]
command = ["/usr/bin/g++", "--static", "main.cpp", "-o", "main"]
sandbox = "embed://policies/cpp.compilebox.toml"

[lang.cpp.execute]
command = ["/hako/main"]
sandbox = "embed://policies/cpp.executebox.toml"


[lang.go]
name = "Golang"

[lang.go.compile]
command = ["/usr/bin/go", "build", "main.go"]
sandbox = "embed://policies/go.compilebox.toml"

[lang.go.execute]
command = ["/hako/main"]
sandbox = "embed://policies/go.executebox.toml"


[lang.java]
name = "Java"

[lang.java.compile]
command = ["/usr/bin/javac", "main.java"]
sandbox = "embed://policies/java.compilebox.toml"

[lang.java.execute]
command = ["/usr/bin/java", "-Xmx256m", "Main"]
sandbox = "embed://policies/java.executebox.toml"
