mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/nodejs-18.8.0", target = "/opt/nodejs-18.8.0" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use --max-old-space-size=256

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"capget",
"clone",
"eventfd2",
"madvise",
"pipe2",
"pkey_alloc",
"pkey_free",
]
