mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/python-3.10.6", target = "/opt/python-3.10.6" },
]

[env]
PATH = "/opt/python-3.10.6/bin"

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "close",
  "connect",
  "dup",
  "execve",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getrandom",
  "getuid",
  "ioctl",
  "lseek",
  "lstat",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "socket",
  "stat",
  "sysinfo",
  "write",
]
