mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/python-3.10.6", target = "/opt/python-3.10.6" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.toml" }}

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "close",
  "connect",
  "dup",
  "execve",
  "exit_group",
  "fcntl",
  "fstat",
  "futex",
  "getcwd",
  "getdents64",
  "getegid",
  "geteuid",
  "getgid",
  "getrandom",
  "getuid",
  "ioctl",
  "lseek",
  "lstat",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "socket",
  "stat",
  "sysinfo",
  "write",
]
