mounts = [
  { source = "/usr/bin/as" , target = "/usr/bin/as"  },
  { source = "/usr/bin/gcc", target = "/usr/bin/gcc" },
  { source = "/usr/bin/ld" , target = "/usr/bin/ld"  },

  { source = "/lib"        , target = "/lib"         },
  { source = "/lib64"      , target = "/lib64"       },
  { source = "/usr/lib"    , target = "/usr/lib"     },
  { source = "/usr/lib64"  , target = "/usr/lib64"   },
  { source = "/usr/include", target = "/usr/include" },
]

[env]
PATH = "/usr/bin"
