[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
nofile = 32     # 32 max fd
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "arch_prctl",
  "brk",
  "execve",
  "exit_group",
  "futex",
  "getrandom",
  "ioctl",
  "mprotect",
  "newfstatat",
  "prlimit64",
  "readlink",
  "rseq",
  "set_robust_list",
  "set_tid_address",
  "write",
]
