mounts = [
  { source = "/usr/bin/go" , target = "/usr/bin/go"  },
  { source = "/lib"        , target = "/lib"         },
  { source = "/lib64"      , target = "/lib64"       },
  { source = "/usr/lib"    , target = "/usr/lib"     },
  { source = "/usr/lib64"  , target = "/usr/lib64"   },
  { source = "/usr/include", target = "/usr/include" },
  { source = "/dev/null"   , target = "/dev/null"     , rw = true },
]

[[files]]
target = "/tmp/.keep"
contents = ""

[env]
HOME = "/hako"
PATH = "/usr/bin"
