mounts = [
  { source = "/usr/bin/java", target = "/usr/bin/java" },
  { source = "/lib"         , target = "/lib"          },
  { source = "/lib64"       , target = "/lib64"        },
  { source = "/usr/lib"     , target = "/usr/lib"      },
  { source = "/usr/lib64"   , target = "/usr/lib64"    },
]

[limits]
fsize = 32000000  # 32MB
walltime = 2      # 2 seconds
