[lang.haskell]
name = "Haskell (GHC 9.4.2)"

[lang.haskell.compile]
command = ["/opt/haskell-9.4.2/.ghcup/bin/ghc", "-dynamic", "main.hs"]
sandbox = ".devcontainer/shared/compilebox.toml"

[lang.haskell.execute]
command = ["/hako/main"]
sandbox = ".devcontainer/lang-haskell/executebox.toml"
