mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/haskell-9.4.2", target = "/opt/haskell-9.4.2" },
]

[env]
LANG     = {{ os_env "LANG"     }}
LANGUAGE = {{ os_env "LANGUAGE" }}
LC_ALL   = {{ os_env "LC_ALL"   }}

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_gettime",
  "clone",
  "close",
  "execve",
  "exit",
  "exit_group",
  "fstat",
  "futex",
  "getrandom",
  "ioctl",
  "lstat",
  "madvise",
  "mmap",
  "mprotect",
  "newfstatat",
  "openat",
  "poll",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "stat",
  "sysinfo",
  "timerfd_create",
  "timerfd_settime",
  "write",
  "writev",
]
