mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/haskell-9.4.2", target = "/opt/haskell-9.4.2" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.toml" }}

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"clone",
"madvise",
"timerfd_create",
"timerfd_settime",
]
