mounts = [
  { source = "/lib"              , target = "/lib"               },
  { source = "/lib64"            , target = "/lib64"             },
  { source = "/usr/lib"          , target = "/usr/lib"           },
  { source = "/usr/lib64"        , target = "/usr/lib64"         },
  { source = "/opt/haskell-9.4.2", target = "/opt/haskell-9.4.2" },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.toml" }}

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_gettime",
  "clone",
  "close",
  "execve",
  "exit",
  "exit_group",
  "fstat",
  "futex",
  "getrandom",
  "ioctl",
  "lstat",
  "madvise",
  "mmap",
  "mprotect",
  "newfstatat",
  "openat",
  "poll",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "set_robust_list",
  "set_tid_address",
  "stat",
  "sysinfo",
  "timerfd_create",
  "timerfd_settime",
  "write",
  "writev",
]
