mounts = [
  { source = "/lib"           , target = "/lib"            },
  { source = "/lib64"         , target = "/lib64"          },
  { source = "/usr/lib"       , target = "/usr/lib"        },
  { source = "/usr/lib64"     , target = "/usr/lib64"      },
  { source = "/opt/openjdk-18", target = "/opt/openjdk-18" },
]

[env]
JAVA_HOME = "/opt/openjdk-18"
PATH = "/opt/openjdk-18/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
