mounts = [
  { source = "/lib"           , target = "/lib"            },
  { source = "/lib64"         , target = "/lib64"          },
  { source = "/usr/lib"       , target = "/usr/lib"        },
  { source = "/usr/lib64"     , target = "/usr/lib64"      },
  { source = "/opt/openjdk-18", target = "/opt/openjdk-18" },
]

[env]
JAVA_HOME = "/opt/openjdk-18"
PATH = "/opt/openjdk-18/bin"

[limits]
# as = 256000000  # use -Xmx256m
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_getres",
  "clock_nanosleep",
  "clone",
  "close",
  "connect",
  "execve",
  "exit",
  "exit_group",
  "faccessat2",
  "fchdir",
  "fcntl",
  "fstat",
  "ftruncate",
  "futex",
  "getcwd",
  "getdents64",
  "geteuid",
  "getpid",
  "getrandom",
  "getrusage",
  "gettid",
  "getuid",
  "ioctl",
  "lseek",
  "madvise",
  "mkdir",
  "mmap",
  "mprotect",
  "munmap",
  "newfstatat",
  "openat",
  "prctl",
  "pread64",
  "prlimit64",
  "read",
  "readlink",
  "rseq",
  "rt_sigaction",
  "rt_sigprocmask",
  "rt_sigreturn",
  "sched_getaffinity",
  "sched_yield",
  "set_robust_list",
  "set_tid_address",
  "stat",
  "socket",
  "sysinfo",
  "uname",
  "unlink",
  "write",
]
