mounts = [
  { source = "/bin"             , target = "/bin"              },
  { source = "/lib"             , target = "/lib"              },
  { source = "/lib64"           , target = "/lib64"            },
  { source = "/usr/bin"         , target = "/usr/bin"          },
  { source = "/usr/lib"         , target = "/usr/lib"          },
  { source = "/usr/lib64"       , target = "/usr/lib64"        },
  { source = "/usr/include"     , target = "/usr/include"      },
  { source = "/etc/alternatives", target = "/etc/alternatives" },
  { source = "/opt/d-2.100.0"   , target = "/opt/d-2.100.0"    },
]

[env]
PATH = "/opt/d-2.100.0/linux/bin64:/usr/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
