mounts = [
  { source = "/usr/bin/as"   , target = "/usr/bin/as"    },
  { source = "/usr/bin/cc"   , target = "/usr/bin/cc"    },
  { source = "/usr/bin/gcc"  , target = "/usr/bin/gcc"   },
  { source = "/usr/bin/ld"   , target = "/usr/bin/ld"    },
  { source = "/lib"          , target = "/lib"           },
  { source = "/lib64"        , target = "/lib64"         },
  { source = "/usr/lib"      , target = "/usr/lib"       },
  { source = "/usr/lib64"    , target = "/usr/lib64"     },
  { source = "/opt/d-2.100.0", target = "/opt/d-2.100.0" },
]

[env]
PATH = "/opt/d-2.100.0/linux/bin64:/usr/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 5      # 5 seconds
