mounts = [
  { source = "/lib"          , target = "/lib"           },
  { source = "/lib64"        , target = "/lib64"         },
  { source = "/usr/lib"      , target = "/usr/lib"       },
  { source = "/usr/lib64"    , target = "/usr/lib64"     },
]

[env]
PATH = "/opt/d-2.100.0/linux/bin64:/usr/bin"

[limits]
as = 256000000  # 256MB
core = 0        # no core file
cpu = 2         # 2 seconds
fsize = 0       # no output file
walltime = 5    # 5 seconds

[seccomp]
syscalls = [
  "access",
  "arch_prctl",
  "brk",
  "clock_getres",
  "close",
  "execve",
  "exit_group",
  "getrandom",
  "mmap",
  "mprotect",
  "newfstatat",
  "openat",
  "pread64",
  "prlimit64",
  "read",
  "rseq",
  "rt_sigaction",
  "sched_getaffinity",
  "sched_yield",
  "set_robust_list",
  "set_tid_address",
  "write",
]
