mounts = [
  { source = "/dev/null"          , target = "/dev/null"            , rw = true },
  { source = "/bin"               , target = "/bin"                },
  { source = "/lib"               , target = "/lib"                },
  { source = "/lib64"             , target = "/lib64"              },
  { source = "/usr/bin"           , target = "/usr/bin"            },
  { source = "/usr/lib"           , target = "/usr/lib"            },
  { source = "/usr/lib64"         , target = "/usr/lib64"          },
  { source = "/usr/share/terminfo", target = "/usr/share/terminfo" },
  { source = "/opt/openjdk-18"    , target = "/opt/openjdk-18"     },
  { source = "/opt/scala-3.1.3"   , target = "/opt/scala-3.1.3"    },
]

[env]
{{ fs_read_to_string ".devcontainer/shared/executebox.env.toml" }}
JAVA_HOME  = "/opt/openjdk-18"
SCALA_HOME = "/opt/scala-3.1.3"

[limits]
{{ fs_read_to_string ".devcontainer/shared/executebox.limits.without_as.toml" }}
# as = 256000000  # use -J-Xmx256m

[seccomp]
syscalls = [
{{ fs_read_to_string ".devcontainer/shared/executebox.seccomp.syscalls.toml" }}

"chdir",
"clone",
"connect",
"dup2",
"dup",
"getrusage",
"madvise",
"pipe2",
"pipe",
"prctl",
"socket",
"wait4",
]
