mounts = [
  { source = "/dev/null"   , target = "/dev/null"     , rw = true },
  { source = "/lib"        , target = "/lib"         },
  { source = "/lib64"      , target = "/lib64"       },
  { source = "/usr/lib"    , target = "/usr/lib"     },
  { source = "/usr/lib64"  , target = "/usr/lib64"   },
  { source = "/opt/go-1.19", target = "/opt/go-1.19" },
]

[[files]]
target = "/tmp/.keep"
contents = ""

[env]
GOCACHE = "/tmp"
PATH = "/opt/go-1.19/bin"

[limits]
fsize = 32000000  # 32MB
walltime = 2      # 2 seconds
